# Generated by Django 6.0.4 on 2026-04-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('subtitulo', models.CharField(help_text='Ex: Web Design / Backend', max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='projetos/')),
                ('tecnologias', models.CharField(help_text='Separe por vírgulas', max_length=200)),
                ('link_github', models.URLField(blank=True)),
                ('link_demo', models.URLField(blank=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição no site')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
