# Generated by Django 6.0.4 on 2026-04-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='subtitulo',
        ),
        migrations.AddField(
            model_name='projeto',
            name='categoria',
            field=models.CharField(default='Geral', help_text='Categoria do projeto (ex: Web, Mobile, API)', max_length=100),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(null=True, upload_to='projetos/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='link_demo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='link_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(help_text='Ex: Plataforma de E-commerce', max_length=200),
        ),
    ]
