# Generated by Django 6.0.4 on 2026-04-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0002_remove_projeto_subtitulo_projeto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('assunto', models.CharField(max_length=200)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Mensagens de Contato',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.CharField(max_length=100)),
                ('bio_curta', models.TextField()),
                ('email_contato', models.EmailField(max_length=254)),
                ('curriculo', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('github_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Perfil',
            },
        ),
        migrations.CreateModel(
            name='RedeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icone_svg', models.CharField(help_text='Ex: instagram.svg', max_length=100)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Redes Sociais',
            },
        ),
        migrations.AlterField(
            model_name='projeto',
            name='categoria',
            field=models.CharField(default='Geral', help_text='Ex: Web, Mobile, API', max_length=100),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(help_text='Mantenha por volta de 167 caracteres para simetria'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(default='projetos/default.jpg', upload_to='projetos/'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='tecnologias',
            field=models.CharField(help_text='Separe por vírgulas (ex: Django, React)', max_length=200),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
