# Generated by Django 6.0.4 on 2026-04-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0003_mensagemcontato_perfil_redesocial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, default='projetos/default.jpg', help_text='Formatos aceitos: JPG, PNG. Padrão: Tech Deep Ocean Icon.', upload_to='projetos/'),
        ),
    ]
