# Generated by Django 6.0.4 on 2026-04-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0004_alter_projeto_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='bio_curta',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='email_contato',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='linkedin_url',
        ),
        migrations.AddField(
            model_name='perfil',
            name='anos_experiencia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='formacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfil/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='status_trabalho',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='curriculo',
            field=models.FileField(default='temp.pdf', upload_to='curriculo/'),
            preserve_default=False,
        ),
    ]
