# Generated by Django 6.0.4 on 2026-04-09 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0005_alter_perfil_options_remove_perfil_bio_curta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='curriculo/'),
        ),
    ]
