# Generated by Django 6.0.4 on 2026-04-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0006_alter_perfil_curriculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bio_curta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
