# Generated by Django 6.0.4 on 2026-04-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0007_perfil_bio_curta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(help_text='Mantenha por volta de 170 caracteres para simetria'),
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='tecnologias',
        ),
        migrations.AddField(
            model_name='projeto',
            name='tecnologias',
            field=models.ManyToManyField(to='app_portfolio.tecnologia'),
        ),
    ]
