# Generated by Django 6.0.4 on 2026-04-10 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0008_tecnologia_alter_projeto_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='link_demo',
        ),
    ]
