# Generated by Django 6.0.4 on 2026-04-10 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0009_remove_projeto_link_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaHabilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('icone', models.CharField(blank=True, help_text='Nome da classe ou arquivo do ícone', max_length=50)),
            ],
            options={
                'verbose_name': 'Categoria de Habilidade',
                'verbose_name_plural': 'Categorias de Habilidades',
            },
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('progresso', models.IntegerField(default=0, help_text='Nível de 0 a 100')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='app_portfolio.categoriahabilidade')),
            ],
        ),
    ]
