# Generated by Django 6.0.4 on 2026-04-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0010_categoriahabilidade_habilidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnologia',
            name='icone',
            field=models.CharField(blank=True, help_text='Ex: python.svg', max_length=100),
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='mostrar_no_home',
            field=models.BooleanField(default=False),
        ),
    ]
