# Generated by Django 6.0.4 on 2026-04-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0011_tecnologia_icone_tecnologia_mostrar_no_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tecnologia',
            options={'ordering': ['ordem', 'nome']},
        ),
        migrations.AddField(
            model_name='tecnologia',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Quanto menor o número, primeiro ele aparece'),
        ),
    ]
