# Generated by Django 6.0.4 on 2026-04-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0012_alter_tecnologia_options_tecnologia_ordem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: 5+ ou 50+', max_length=10)),
                ('legenda', models.CharField(help_text='Ex: Anos de Experiência', max_length=50)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a posição de exibição')),
            ],
            options={
                'verbose_name': 'Estatística',
                'verbose_name_plural': 'Estatísticas',
                'ordering': ['ordem'],
            },
        ),
        migrations.AlterModelOptions(
            name='mensagemcontato',
            options={'ordering': ['-data_envio'], 'verbose_name': 'Mensagem de Contato', 'verbose_name_plural': 'Mensagens de Contato'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil', 'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['ordem'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterModelOptions(
            name='redesocial',
            options={'verbose_name': 'Rede Social', 'verbose_name_plural': 'Redes Sociais'},
        ),
        migrations.AlterModelOptions(
            name='tecnologia',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Tecnologia', 'verbose_name_plural': 'Tecnologias'},
        ),
    ]
