# Generated by Django 6.0.4 on 2026-04-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0013_estatistica_alter_mensagemcontato_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estatistica',
            name='destaque_sobre',
            field=models.BooleanField(default=False, verbose_name='Destaque na foto Sobre Mim'),
        ),
    ]
