# Generated by Django 6.0.4 on 2026-04-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0014_estatistica_destaque_sobre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estatistica',
            name='legenda',
            field=models.TextField(help_text="Dê um 'Enter' onde deseja quebrar a linha", max_length=100),
        ),
    ]
