# Generated by Django 6.0.4 on 2026-04-10 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0015_alter_estatistica_legenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('slug', models.SlugField(help_text='Nome usado no filtro (ex: web, api, mobile)', unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Projeto',
                'verbose_name_plural': 'Categorias de Projetos',
            },
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='projeto',
            name='categoria_projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='app_portfolio.categoriaprojeto'),
        ),
    ]
