# Generated by Django 6.0.4 on 2026-04-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0016_categoriaprojeto_remove_projeto_categoria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RedeSocial',
        ),
    ]
