# Generated by Django 6.0.4 on 2026-04-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0017_delete_redesocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='email_contato',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
