# Generated by Django 6.0.4 on 2026-04-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0018_perfil_email_contato_perfil_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='link_github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='link_linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
