# Generated by Django 6.0.4 on 2026-04-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0019_perfil_link_github_perfil_link_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='mostrar_progresso',
            field=models.BooleanField(default=False, help_text='Marque para exibir as porcentagens de domínio nas habilidades.', verbose_name='Exibir barras de progresso'),
        ),
    ]
