# Generated by Django 6.0.4 on 2026-04-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_portfolio", "0020_perfil_mostrar_progresso"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perfil",
            name="foto",
            field=models.ImageField(
                blank=True,
                help_text="Sua foto de apresentação. Será convertida para WebP para agilizar o carregamento da Home.",
                null=True,
                upload_to="perfil/",
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="imagem",
            field=models.ImageField(
                blank=True,
                help_text="Upload em JPG ou PNG. O sistema converterá para WebP automaticamente para performance.",
                null=True,
                upload_to="projetos/",
            ),
        ),
    ]
