# Generated by Django 6.0.4 on 2026-09-11 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0021_alter_perfil_foto_alter_projeto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagemcontato',
            name='mensagem',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
    ]
